window.esdocSearchIndex = [
  [
    "@neurosity/pipes/src/constants/index.js~channels",
    "variable/index.html#static-variable-CHANNELS",
    "<span>CHANNELS</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~characteristic",
    "variable/index.html#static-variable-CHARACTERISTIC",
    "<span>CHARACTERISTIC</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~data_prop",
    "variable/index.html#static-variable-DATA_PROP",
    "<span>DATA_PROP</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~epoch_duration",
    "variable/index.html#static-variable-EPOCH_DURATION",
    "<span>EPOCH_DURATION</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~epoch_interval",
    "variable/index.html#static-variable-EPOCH_INTERVAL",
    "<span>EPOCH_INTERVAL</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~fft_bins",
    "variable/index.html#static-variable-FFT_BINS",
    "<span>FFT_BINS</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~frequency_bands",
    "variable/index.html#static-variable-FREQUENCY_BANDS",
    "<span>FREQUENCY_BANDS</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~gain",
    "variable/index.html#static-variable-GAIN",
    "<span>GAIN</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~notch_bw",
    "variable/index.html#static-variable-NOTCH_BW",
    "<span>NOTCH_BW</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~order",
    "variable/index.html#static-variable-ORDER",
    "<span>ORDER</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~pregain",
    "variable/index.html#static-variable-PREGAIN",
    "<span>PREGAIN</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~sampling_rate",
    "variable/index.html#static-variable-SAMPLING_RATE",
    "<span>SAMPLING_RATE</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/constants/index.js~use_log",
    "variable/index.html#static-variable-USE_LOG",
    "<span>USE_LOG</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/constants/index.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/addinfo.js~addinfo",
    "function/index.html#static-function-addInfo",
    "<span>addInfo</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/addInfo.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/addsignalquality.js~addsignalquality",
    "function/index.html#static-function-addSignalQuality",
    "<span>addSignalQuality</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/addSignalQuality.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/alphapower.js~alphapower",
    "function/index.html#static-function-alphaPower",
    "<span>alphaPower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/alphaPower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~average",
    "variable/index.html#static-variable-average",
    "<span>average</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "variable"
  ],
  [
    "@neurosity/pipes/src/pipes/reducer/averagedeep.js~averagedeep",
    "function/index.html#static-function-averageDeep",
    "<span>averageDeep</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/reducer/averageDeep.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/averagepower.js~averagepower",
    "function/index.html#static-function-averagePower",
    "<span>averagePower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/averagePower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/filtering/bandpassfilter.js~bandpassfilter",
    "function/index.html#static-function-bandpassFilter",
    "<span>bandpassFilter</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/filtering/bandpassFilter.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/betapower.js~betapower",
    "function/index.html#static-function-betaPower",
    "<span>betaPower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/betaPower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/bufferfft.js~bufferfft",
    "function/index.html#static-function-bufferFFT",
    "<span>bufferFFT</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/bufferFFT.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/buffertoepoch.js~buffertoepoch",
    "function/index.html#static-function-bufferToEpoch",
    "<span>bufferToEpoch</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/bufferToEpoch.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/createeeg.js~createeeg",
    "function/index.html#static-function-createEEG",
    "<span>createEEG</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/createEEG.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/createmockstream.js~createmockstream",
    "function/index.html#static-function-createMockStream",
    "<span>createMockStream</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/createMockStream.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/deltapower.js~deltapower",
    "function/index.html#static-function-deltaPower",
    "<span>deltaPower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/deltaPower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/epoch.js~epoch",
    "function/index.html#static-function-epoch",
    "<span>epoch</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/epoch.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/fft.js~fft",
    "function/index.html#static-function-fft",
    "<span>fft</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/fft.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/gammapower.js~gammapower",
    "function/index.html#static-function-gammaPower",
    "<span>gammaPower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/gammaPower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/groupbychannel.js~groupbychannel",
    "function/index.html#static-function-groupByChannel",
    "<span>groupByChannel</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/groupByChannel.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/filtering/highpassfilter.js~highpassfilter",
    "function/index.html#static-function-highpassFilter",
    "<span>highpassFilter</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/filtering/highpassFilter.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/isepoch.js~isepoch",
    "function/index.html#static-function-isEpoch",
    "<span>isEpoch</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/isEpoch.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/filtering/lowpassfilter.js~lowpassfilter",
    "function/index.html#static-function-lowpassFilter",
    "<span>lowpassFilter</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/filtering/lowpassFilter.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~max",
    "function/index.html#static-function-max",
    "<span>max</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~mean",
    "function/index.html#static-function-mean",
    "<span>mean</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~meanabsolutedeviation",
    "function/index.html#static-function-meanAbsoluteDeviation",
    "<span>meanAbsoluteDeviation</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/filtering/notchfilter.js~notchfilter",
    "function/index.html#static-function-notchFilter",
    "<span>notchFilter</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/filtering/notchFilter.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/pickchannels.js~pickchannels",
    "function/index.html#static-function-pickChannels",
    "<span>pickChannels</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/pickChannels.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/powerbyband.js~powerbyband",
    "function/index.html#static-function-powerByBand",
    "<span>powerByBand</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/powerByBand.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~range",
    "function/index.html#static-function-range",
    "<span>range</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/utility/removechannels.js~removechannels",
    "function/index.html#static-function-removeChannels",
    "<span>removeChannels</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/utility/removeChannels.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/slicefft.js~slicefft",
    "function/index.html#static-function-sliceFFT",
    "<span>sliceFFT</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/sliceFFT.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~standarddeviation",
    "function/index.html#static-function-standardDeviation",
    "<span>standardDeviation</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~sum",
    "function/index.html#static-function-sum",
    "<span>sum</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/frequency/thetapower.js~thetapower",
    "function/index.html#static-function-thetaPower",
    "<span>thetaPower</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/frequency/thetaPower.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/stats.js~variance",
    "function/index.html#static-function-variance",
    "<span>variance</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/stats.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/pipes/unit/voltstomicrovolts.js~voltstomicrovolts",
    "function/index.html#static-function-voltsToMicrovolts",
    "<span>voltsToMicrovolts</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/pipes/unit/voltsToMicrovolts.js</span>",
    "function"
  ],
  [
    "@neurosity/pipes/src/utils/zeropad.js~zeropad",
    "function/index.html#static-function-zeroPad",
    "<span>zeroPad</span> <span class=\"search-result-import-path\">@neurosity/pipes/src/utils/zeroPad.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/constants/index.js",
    "file/src/constants/index.js.html",
    "src/constants/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/pipes/filtering/bandpassfilter.js",
    "file/src/pipes/filtering/bandpassFilter.js.html",
    "src/pipes/filtering/bandpassFilter.js",
    "file"
  ],
  [
    "src/pipes/filtering/highpassfilter.js",
    "file/src/pipes/filtering/highpassFilter.js.html",
    "src/pipes/filtering/highpassFilter.js",
    "file"
  ],
  [
    "src/pipes/filtering/index.js",
    "file/src/pipes/filtering/index.js.html",
    "src/pipes/filtering/index.js",
    "file"
  ],
  [
    "src/pipes/filtering/lowpassfilter.js",
    "file/src/pipes/filtering/lowpassFilter.js.html",
    "src/pipes/filtering/lowpassFilter.js",
    "file"
  ],
  [
    "src/pipes/filtering/notchfilter.js",
    "file/src/pipes/filtering/notchFilter.js.html",
    "src/pipes/filtering/notchFilter.js",
    "file"
  ],
  [
    "src/pipes/frequency/alphapower.js",
    "file/src/pipes/frequency/alphaPower.js.html",
    "src/pipes/frequency/alphaPower.js",
    "file"
  ],
  [
    "src/pipes/frequency/averagepower.js",
    "file/src/pipes/frequency/averagePower.js.html",
    "src/pipes/frequency/averagePower.js",
    "file"
  ],
  [
    "src/pipes/frequency/betapower.js",
    "file/src/pipes/frequency/betaPower.js.html",
    "src/pipes/frequency/betaPower.js",
    "file"
  ],
  [
    "src/pipes/frequency/bufferfft.js",
    "file/src/pipes/frequency/bufferFFT.js.html",
    "src/pipes/frequency/bufferFFT.js",
    "file"
  ],
  [
    "src/pipes/frequency/deltapower.js",
    "file/src/pipes/frequency/deltaPower.js.html",
    "src/pipes/frequency/deltaPower.js",
    "file"
  ],
  [
    "src/pipes/frequency/fft.js",
    "file/src/pipes/frequency/fft.js.html",
    "src/pipes/frequency/fft.js",
    "file"
  ],
  [
    "src/pipes/frequency/gammapower.js",
    "file/src/pipes/frequency/gammaPower.js.html",
    "src/pipes/frequency/gammaPower.js",
    "file"
  ],
  [
    "src/pipes/frequency/index.js",
    "file/src/pipes/frequency/index.js.html",
    "src/pipes/frequency/index.js",
    "file"
  ],
  [
    "src/pipes/frequency/powerbyband.js",
    "file/src/pipes/frequency/powerByBand.js.html",
    "src/pipes/frequency/powerByBand.js",
    "file"
  ],
  [
    "src/pipes/frequency/slicefft.js",
    "file/src/pipes/frequency/sliceFFT.js.html",
    "src/pipes/frequency/sliceFFT.js",
    "file"
  ],
  [
    "src/pipes/frequency/thetapower.js",
    "file/src/pipes/frequency/thetaPower.js.html",
    "src/pipes/frequency/thetaPower.js",
    "file"
  ],
  [
    "src/pipes/index.js",
    "file/src/pipes/index.js.html",
    "src/pipes/index.js",
    "file"
  ],
  [
    "src/pipes/reducer/averagedeep.js",
    "file/src/pipes/reducer/averageDeep.js.html",
    "src/pipes/reducer/averageDeep.js",
    "file"
  ],
  [
    "src/pipes/reducer/index.js",
    "file/src/pipes/reducer/index.js.html",
    "src/pipes/reducer/index.js",
    "file"
  ],
  [
    "src/pipes/unit/index.js",
    "file/src/pipes/unit/index.js.html",
    "src/pipes/unit/index.js",
    "file"
  ],
  [
    "src/pipes/unit/voltstomicrovolts.js",
    "file/src/pipes/unit/voltsToMicrovolts.js.html",
    "src/pipes/unit/voltsToMicrovolts.js",
    "file"
  ],
  [
    "src/pipes/utility/addinfo.js",
    "file/src/pipes/utility/addInfo.js.html",
    "src/pipes/utility/addInfo.js",
    "file"
  ],
  [
    "src/pipes/utility/addsignalquality.js",
    "file/src/pipes/utility/addSignalQuality.js.html",
    "src/pipes/utility/addSignalQuality.js",
    "file"
  ],
  [
    "src/pipes/utility/buffercount.js",
    "file/src/pipes/utility/bufferCount.js.html",
    "src/pipes/utility/bufferCount.js",
    "file"
  ],
  [
    "src/pipes/utility/buffertime.js",
    "file/src/pipes/utility/bufferTime.js.html",
    "src/pipes/utility/bufferTime.js",
    "file"
  ],
  [
    "src/pipes/utility/buffertoepoch.js",
    "file/src/pipes/utility/bufferToEpoch.js.html",
    "src/pipes/utility/bufferToEpoch.js",
    "file"
  ],
  [
    "src/pipes/utility/epoch.js",
    "file/src/pipes/utility/epoch.js.html",
    "src/pipes/utility/epoch.js",
    "file"
  ],
  [
    "src/pipes/utility/index.js",
    "file/src/pipes/utility/index.js.html",
    "src/pipes/utility/index.js",
    "file"
  ],
  [
    "src/pipes/utility/pickchannels.js",
    "file/src/pipes/utility/pickChannels.js.html",
    "src/pipes/utility/pickChannels.js",
    "file"
  ],
  [
    "src/pipes/utility/removechannels.js",
    "file/src/pipes/utility/removeChannels.js.html",
    "src/pipes/utility/removeChannels.js",
    "file"
  ],
  [
    "src/utils/createeeg.js",
    "file/src/utils/createEEG.js.html",
    "src/utils/createEEG.js",
    "file"
  ],
  [
    "src/utils/createmockstream.js",
    "file/src/utils/createMockStream.js.html",
    "src/utils/createMockStream.js",
    "file"
  ],
  [
    "src/utils/groupbychannel.js",
    "file/src/utils/groupByChannel.js.html",
    "src/utils/groupByChannel.js",
    "file"
  ],
  [
    "src/utils/index.js",
    "file/src/utils/index.js.html",
    "src/utils/index.js",
    "file"
  ],
  [
    "src/utils/isepoch.js",
    "file/src/utils/isEpoch.js.html",
    "src/utils/isEpoch.js",
    "file"
  ],
  [
    "src/utils/stats.js",
    "file/src/utils/stats.js.html",
    "src/utils/stats.js",
    "file"
  ],
  [
    "src/utils/zeropad.js",
    "file/src/utils/zeroPad.js.html",
    "src/utils/zeroPad.js",
    "file"
  ]
]